spring.application.name=sneaker-backend
spring.datasource.url=jdbc:mysql://localhost:3306/sneaker_shop
spring.datasource.username=root
spring.datasource.password=
spring.config.import=optional:application-secret.properties
# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=haduyphamvo@gmail.com
spring.mail.password=psvz fdru nozt fycc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true